=== DanielFran/jhipster-base/src/JDLApplicationOptions.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": [],
    "additionalItems": true,
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "description": "An explanation about the purpose of this instance.",
        "default": {},
        "examples": [
            {
                "option": "applicationType",
                "baseType": "STRING",
                "values": [
                    "monolith",
                    "microservice",
                    "gateway",
                    "uaa"
                ],
                "description": "",
                "parseType": "Literal"
            },
            {
                "values": [
                    "Entity"
                ],
                "description": "Suffix for entities. false for empty string",
                "parseType": "JavaIdentifierLiteral",
                "option": "entitySuffix",
                "baseType": "STRING"
            },
            {
                "parseType": "Literal",
                "option": "serviceDiscoveryType",
                "baseType": "STRING",
                "values": [
                    "eureka",
                    "consul",
                    "no",
                    "false"
                ],
                "description": ""
            }
        ],
        "additionalProperties": true,
        "required": [
            "option",
            "baseType",
            "parseType",
            "values",
            "description"
        ],
        "properties": {
            "option": {
                "$id": "#/items/properties/option",
                "type": "string",
                "title": "The Option Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "applicationType"
                ]
            },
            "baseType": {
                "$id": "#/items/properties/baseType",
                "type": "string",
                "title": "The Basetype Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "STRING"
                ]
            },
            "parseType": {
                "$id": "#/items/properties/parseType",
                "type": "string",
                "title": "The Parsetype Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "Literal"
                ]
            },
            "values": {
                "$id": "#/items/properties/values",
                "type": "array",
                "title": "The Values Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": [],
                "examples": [
                    [
                        "monolith",
                        "microservice",
                        "gateway"
                    ]
                ],
                "additionalItems": true,
                "items": {
                    "$id": "#/items/properties/values/items",
                    "type": "string",
                    "title": "The Items Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "monolith",
                        "microservice",
                        "gateway"
                    ]
                }
            },
            "description": {
                "$id": "#/items/properties/description",
                "type": "string",
                "title": "The Description Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    ""
                ]
            }
        }
    }
}

=== DanielFran/jhipster-base/src/JDLOptions.json
[
  {
    "option": "angularSuffix",
    "baseType": "STRING",
    "parseType": "Literal",
    "values": [],
    "description": "The suffix angular files should have, the dash prefix is optional for this option."
  },
  {
    "option": "clientRootFolder",
    "baseType": "STRING",
    "parseType": "Literal",
    "values": [],
    "description": "The base folder where client files are set up."
  },
  {
    "option": "dto",
    "baseType": "STRING",
    "parseType": "Literal",
    "values": [
      "mapstruct",
      "no"
    ],
    "description": "Whether to create DTOs for your entities, if an entity has a DTO but no service, then 'serviceClass' will be used for the service option."
  },
  {
    "option": "embedded",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "true"
    ],
    "description": "Whether an entity is embedded inside others."
  },
  {
    "option": "filter",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "true"
    ],
    "description": "Whether to enable JPA metamodel filtering on an entity."
  },
  {
    "option": "microservice",
    "baseType": "STRING",
    "parseType": "Literal",
    "values": [],
    "description": "The value is set to be the application's name for each entity in an application, and isn't set when application isn't a microservice."
  },
  {
    "option": "noFluentMethod",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "false"
    ],
    "description": "Whether to turn off the generation of fluent methods."
  },
  {
    "option": "pagination",
    "baseType": "STRING",
    "parseType": "Literal",
    "values": [
      "infinite-scroll",
      "pagination",
      "no"
    ],
    "description": ""
  },
  {
    "option": "readOnly",
    "baseType": "BOOLEAN",
    "parseType": "Boolean",
    "values": [
      "false"
    ],
    "description": "Whether to turn off front-end and back-end code generation to create, update or delete entities."
  },
  {
    "option": "search",
    "baseType": "STRING",
    "parseType": "Literal",
    "values": [
      "couchbase",
      "elasticsearch",
      "no"
    ],
    "description": ""
  },
  {
    "option": "service",
    "baseType": "STRING",
    "parseType": "Literal",
    "values": [
      "serviceClass",
      "serviceImpl",
      "no"
    ],
    "description": ""
  },
  {
    "option": "skipClient",
    "baseType": "Boolean",
    "parseType": "boolean",
    "values": [
      "false"
    ],
    "description": "Whether to skip front-end code generation."
  },
  {
    "option": "skipServer",
    "baseType": "Boolean",
    "parseType": "boolean",
    "values": [
      "false"
    ],
    "description": "Whether to skip back-end code generation."
  }
]
